In [81]:
mat <- c(0.01, 0.03, 0.05, 0.09 )

In [82]:
matrix(mat, nrow=3)

Warning message:
In matrix(mat, nrow = 3): data length [4] is not a sub-multiple or multiple of the number of rows [3]

[,1] [,2]
[1,] 0.01 0.09
[2,] 0.03 0.01
[3,] 0.05 0.03

In [83]:
# calcul le produit des (1+ri)
prod <- function(tab, n){
  tmp = 1;
  for (i in (1:n)){
    tmp = tmp * (1+ 0.01*tab[i]);
  }
  return(tmp);
}


#La collection des taux futurs la suite(ri^n)
futur <- function(tauxInit, tabTaux, size){
    tab <- c();
    for( i in (1:size)){
        tab = append(tab,0);
    }
    
  tmp = tauxInit;
  tab[1] = tauxInit;

    for (i in (2:size)){
        tmp = (1 + tabTaux[i])**i / ((1 + tauxInit)* prod(tab, size)) - 1;
        tab[i] = tmp;
      }
    
  return(matrix(tab, nrow=1))
}



In [84]:
prod(mat, 3)

[1] 1.0009

In [85]:
print(futur(0.03,mat,3))

     [,1]       [,2]      [,3]
[1,] 0.03 0.02969109 0.1232372


In [131]:
# calcul le produit des (1+ri)
prod2 <- function(tab, n, index){
  tmp = 1;
  for (i in (1:n)){
    tmp = tmp * (1+ 0.01*tab[i, index]);
  }
  return(tmp);
}


taux<-function(tauxInit, tabTaux, size){
    tmp = 0;
    mat = matrix(tabTaux, ncol=size)
    
    tab1 <- c();
    for( i in (1:size*size)){
        tab1 = append(tab1,0);
    }
    
    tab <- matrix(tab1, ncol=size);
 
    for(j in (2:size)){
         tab[1,j] = tauxInit[j];
        for (i in (2:size)){
            tmp = (1 + tabTaux[j,i])**i / ((1 + tauxInit[j])* prod2(tab, size, index)) - 1;
            tab[i,j] = tmp;
          }
        }
}

In [135]:
tab1 <- c(0.02, 0.05, 0.06, 0.07);
tab2 <- c(0.02, 0.06, 0.06, 0.07);
tab3 <- c(0.02, 0.07, 0.06, 0.07);
tab4 <- c(0.02, 0.07, 0.08, 0.07);

mat <- c(tab1, tab2, tab3, tab4);
tabInit <- c(0.02, 0.05, 0.06, 0.07); 

taux(tabInit,mat,4)

ERROR: Error in tabTaux[j, i]: incorrect number of dimensions


In [136]:
mat
m = matrix(mat,ncol=4)
m
m[3,3]

[1] 0.02 0.05 0.06 0.07 0.02 0.06 0.06 0.07 0.02 0.07 0.06 0.07 0.02 0.07 0.08
[16] 0.07

[,1] [,2] [,3] [,4]
[1,] 0.02 0.02 0.02 0.02
[2,] 0.05 0.06 0.07 0.07
[3,] 0.06 0.06 0.06 0.08
[4,] 0.07 0.07 0.07 0.07

[1] 0.06

In [137]:
size = 3
for(i in (1:size)){
        index = (i-1)*size+i;
    print(index)
    }

[1] 1
[1] 5
[1] 9
